# Generated by Django 4.1.4 on 2023-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=150)),
            ],
        ),
    ]
