# Generated by Django 4.1.4 on 2023-01-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_tempdoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdoc',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='tempdoc',
            name='LastName',
        ),
    ]
