# Generated by Django 4.1.4 on 2023-01-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_tempdoc_firstname_remove_tempdoc_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.tempdoc'),
        ),
    ]
